spring:
  profiles:
    default: local
    group:
      local:
        - console-logging
      dev:
        - console-logging
        - file-warn-logging
        - file-error-logging
        - slack-error-logging
