name: "\U0001F41E Bug"
description: "개발 도중 버그가 발생했나요?"
labels: "\U0001F41E Bug"
body:
  - type: textarea
    attributes:
      label: 🐞 설명
      description: 버그에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📄 버그 로그
      description: 로그가 있으면 복붙해 주세요.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🌏 버그 발생 환경
      description: 버그가 발생한 환경에 대해 작성해 주세요.
      placeholder: |
        OS: macOS
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 버그 재현 방법
      description: Given-When-Then 형식으로 버그를 재현할 수 있는 방법에 대해 작성해 주세요.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 발생한 버그에 대한 참고 자료가 있다면 작성해 주세요.
    validations:
      required: false
  - type: textarea
    attributes:
      label: ⏰ 추정 시간
      description: 버그를 해결하기 위한 추정 시간에 대해 작성해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ⏰ 소요 시간
      description: 버그 해결 소요 시간에 대해 작성해주세요.
    validations:
      required: true
