version: "3.9"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
      
